export const filterTypes = {
  RATING_ASC: "RATING ASCENDING",
  RATING_DESC: "RATING DESCENDING",
  YEAR_ASC: "YEAR ASCENDING",
  YEAR_DESC: "YEAR DESCENDING",
  GENRES_ADD: "ADD GENRE",
  GENRES_REMOVE: "REMOVE GENRE",
  ADD_FILTERED: "ADD FILTERED",
};
